kind: Deployment
apiVersion: apps/v1
metadata:
  name: forex-miner-thor
  namespace: forex-miner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: forex-miner-thor
  template:
    metadata:
      labels:
        app: forex-miner-thor
    spec:
      containers:
        - name: forex-miner-thor
          image: ghcr.io/geriremenyi/forex-miner-thor:0.0.1
          ports:
            - containerPort: 31001
          volumeMounts:
            - mountPath: "/app/data"
              name: data-volume
      imagePullSecrets:
        - name: ghcr-secret
      nodeSelector:
        agentpool: fmnpbe
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: forex-miner-thor-storage