apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: forex-miner-thor-storage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: 1Gi