apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: forex-miner-thor-storage
  namespace: forex-miner
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: 1Gi